config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get "/" => "site#home"

  get "/clientuser" => "site#clientuser"

  get "/pendientes" => "deliveries#pendientes"

  post "/update/pendientes/:id" => "deliveries#pending"

  get "/ver_cargas" => "deliveries#ver_cargas"

  get "/transportes" => "deliveries#index"

  post "/customreport" => "site#customreport"

  post "/deliveredreport" => "site#deliveredreport"

  post "/patsea" => "site#patsea"

  resources :clients, only: [:update, :edit, :show, :new, :index, :create, :destroy] do
  	resources :deliveries, only: [ :update, :edit, :show, :new, :create, :destroy]
  end

  resources :trucks, only: [:update, :edit, :show, :new, :index, :create, :destroy]

  resources :drivers, only: [:update, :edit, :show, :new, :index, :create, :destroy]
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :deliveries
	has_many :places, through: :deliveries
	has_many :vehicles, through: :deliveries
end

app/controllers/clients_controller.rb
require 'pry'
class ClientsController < ApplicationController
	def new
		@client = Client.new
	end

	def create
		@client = Client.new(client_params)
		if(@client.save)
			redirect_to(client_path(@client))
		else
			render('new')
		end
	end

	def show
		@client = Client.find(params[:id])
	end

	def destroy
		@client = Client.find(params[:id])
		@client.destroy
	end

	def index
		@clients = Client.all
	end

	def edit
		@client = Client.find(params[:id])
	end

	def update
		@client = Client.find(params[:id])
		@client.update(client_params)
		redirect_to(client_path(@client))
	end

	private

	def client_params
		params.require(:client).permit(:nif, :name, :street, :street_number, :city, :postal_code, :phone, :email, :contact_person, :observations, :payment_method)		
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/destroy.html.erb
<div>
	<h2>El cliente <%= @client.name %> ha sido eliminado</h2>
</div>

app/views/clients/edit.html.erb
<div id="edit-client">
	<h2>Editando <%= @client.name %></h2>

	<%= form_for(@client) do |f| %>
		<%= f.label "Nombre" %>
		<%= f.text_field :name, class: 'form-control'%>
		<br>
		<%= f.label "Nif o CIF" %>
		<%= f.text_field :nif, class: 'form-control'%>
		<br>
		<%= f.label "Calle" %>
		<%= f.text_field :street, class: 'form-control'%>
		<br>
		<%= f.label "Numero y resto dirección" %>
		<%= f.text_field :street_number, class: 'form-control'%>
		<br>
		<%= f.label "Ciudad" %>
		<%= f.text_field :city, class: 'form-control'%>
		<br>
		<%= f.label "Código postal" %>
		<%= f.text_field :postal_code, class: 'form-control'%>
		<br>
		<%= f.label "Telefono" %>
		<%= f.text_field :phone, class: 'form-control'%>
		<br>
		<%= f.label "email" %>
		<%= f.text_field :email, class: 'form-control'%>
		<br>
		<%= f.label "Persona de contacto" %>
		<%= f.text_field :contact_person, class: 'form-control'%>
		<br>
		<%= f.label "Observaciones" %>
		<%= f.text_field :observations, class: 'form-control'%>
		<br>
		<%= f.select(:payment_method, ['Efectivo', 'Transferencia', 'Recibo'], {include_blank: "Seleccionar metodo"}, {:class => 'browser-default'}) %>
  		<%= f.submit "Guardar cambios" %>
	<% end %>
</div> 

app/views/clients/index.html.erb
<div class="client-list">
	<ul class="collection">
		<% @clients.order(name: :asc).each do |client| %>
		<li class="collection-item"> <%= link_to(client.name, client_path(client)) %> <div class="index-buttons"> <%= link_to 'Eliminar',  client,  method: :delete, data: { confirm: '¿Estas seguro?' } %> <%= link_to('Editar', edit_client_path(client)) %> - <%= link_to('Nueva solicitud', new_client_delivery_path(client)) %>
		</div> </li>
		<% end %>
	</ul>
</div> 

app/views/clients/new.html.erb
<div id="new-client">
	<h2>Crear un nuevo cliente</h2>

	<%= form_for [@client] do |f| %>
		<%= f.label "Nombre" %>
		<%= f.text_field :name%>
		<br>
		<%= f.label "Nif o CIF" %>
		<%= f.text_field :nif%>
		<br>
		<%= f.label "Calle" %>
		<%= f.text_field :street%>
		<br>
		<%= f.label "Numero y resto dirección" %>
		<%= f.text_field :street_number%>
		<br>
		<%= f.label "Ciudad" %>
		<%= f.text_field :city%>
		<br>
		<%= f.label "Código postal" %>
		<%= f.text_field :postal_code%>
		<br>
		<%= f.label "Telefono" %>
		<%= f.text_field :phone%>
		<br>
		<%= f.label "email" %>
		<%= f.text_field :email%>
		<br>
		<%= f.label "Persona de contacto" %>
		<%= f.text_field :contact_person%>
		<br>
		<%= f.label "Observaciones" %>
		<%= f.text_field :observations%>
		<br>
		<%= f.select(:payment_method, ['Efectivo', 'Transferencia', 'Recibo'], {include_blank: "Seleccionar metodo"}, {:class => 'browser-default'}) %>
  		<%= f.submit "Dar de alta" %>
	<% end %>
</div> 

app/views/clients/show.html.erb
<div class="client-show center-align">
	   <div class="row">
        <div class="col s12 m12">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title"><%= @client.name %></span>
              <p>NIF: <%= @client.nif %></p>
              <p>Direccion: <%= @client.street %> - <%= @client.street_number %></p>
              <p>Ciudad: <%= @client.city %> - CP: <%= @client.postal_code %></p>
              <p>Télefono: <%= @client.phone %></p>
              <p>Email: <%= @client.email %></p>
              <p>Persona de contacto: <%= @client.contact_person %></p>
              <p>Observaciones: <%= @client.observations %></p>
              <p>Metodo de pago por defecto: <%= @client.payment_method %></p>
            </div>
            <div class="card-action">
            <%= link_to 'Eliminar',  @client,  method: :delete, data: { confirm: '¿Estas seguro?' } %>
              <%= link_to('Editar', edit_client_path(@client)) %>
            </div>
          </div>
        </div>
      </div>
</div>