config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get "/" => "site#home"

  get "/clientuser" => "site#clientuser"

  get "/pendientes" => "deliveries#pendientes"

  post "/update/pendientes/:id" => "deliveries#pending"

  get "/ver_cargas" => "deliveries#ver_cargas"

  get "/transportes" => "deliveries#index"

  post "/customreport" => "site#customreport"

  post "/deliveredreport" => "site#deliveredreport"

  post "/patsea" => "site#patsea"

  resources :clients, only: [:update, :edit, :show, :new, :index, :create, :destroy] do
  	resources :deliveries, only: [ :update, :edit, :show, :new, :create, :destroy]
  end

  resources :trucks, only: [:update, :edit, :show, :new, :index, :create, :destroy]

  resources :drivers, only: [:update, :edit, :show, :new, :index, :create, :destroy]
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
	belongs_to :client
	has_many :vehicles
	has_many :places

	has_attached_file :document
	validates_attachment :document, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)}

end

app/controllers/deliveries_controller.rb
require 'pry'
class DeliveriesController < ApplicationController
	def new
		@client = Client.find(params[:client_id])
	end

	def destroy
		@delivery = Delivery.find(params[:id])
		@delivery.destroy
		redirect_to("/")
	end

	def show
		@client = Client.find(params[:client_id])
		@delivery = Delivery.find(params[:id])
		@vehicle = Vehicle.find(@delivery.vehicle)
		@origin = Place.find(@delivery.origin)
		@destiny = Place.find(@delivery.destination)
		@truck = Truck.all
		@driver = Driver.all
	end

	def index
		@deliveries = Delivery.all.limit(15)
		@vehicles = Vehicle.all
		@places = Place.all
	end

	def create
		@client = Client.find(params[:client_id])
		@delivery = @client.deliveries.new(observations: params[:observaciones])
		
		if @delivery.save
			@origin = @delivery.places.create(name: params[:origenEmpresa], address: params[:origenDireccion], address_details: params[:origenDetalles], postal_code: params[:origenCP], city: params[:origenCiudad], phone: params[:origenTelefono], contact_person: params[:origenContacto])
			@destiny = @delivery.places.create(name: params[:destinoEmpresa], address: params[:destinoDireccion], address_details: params[:destinoDetalles], postal_code: params[:destinoCP], city: params[:destinoCiudad], phone: params[:destinoTelefono], contact_person: params[:destinoContacto])
			@vehicle = @delivery.vehicles.create(bastidor_matricula: params[:basmat], model: params[:modelo], brand: params[:marca], observations: params[:observaciones])
			if params[:picture] != nil
				@delivery.update(document: params[:picture])
			end
			@delivery.update(origin: @origin.id, destination: @destiny.id, vehicle: @vehicle.id)
			NewJob.send_new_job_info(@client, @delivery, @vehicle, @origin, @destiny).deliver
			redirect_to(client_delivery_path(@client, @delivery))
		else
			render 'new'
		end

	end

	def edit
		@client = Client.find(params[:client_id])
		@delivery = Delivery.find(params[:id])
	end

	def update
		@delivery = Delivery.find(params[:id])
		@delivery.update(delivery_params)
		redirect_to(client_delivery_path(params[:client_id], params[:id]))
	end

	def pendientes
		@deliveries = Delivery.where(delivery_status: "PENDIENTE")
		@vehicles = Vehicle.all
		@places = Place.all
	end

	def pending
		@delivery = Delivery.find(params[:id])
		@delivery.update(price: params[:precio], driver_price: params[:precioConductor], truck: params[:camion], driver: params[:conductor], delivery_status: params[:estado])
		redirect_to(client_delivery_path(@delivery.client.id, @delivery))
	end	

	def ver_cargas
		@trucks = Truck.all
		@deliveries = Delivery.where(delivery_status: 'CARGADO')
		@places = Place.all
		@vehicles = Vehicle.all
	end

	private

	def delivery_params
		params.require(:delivery).permit(:payment_status, :payment_date, :payment_method, :price, :driver_price, :truck, :driver, :delivery_status, :delivery_date)
	end
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/views/deliveries/edit.html.erb
<div id="delivery-edit">
	<h2>Editando solicitud nº: <%= @delivery.id %></h2>

	<%= form_for [@client, @delivery] do |f| %>
		<%= f.label "Precio" %>
		<%= f.text_field :price, class: 'form-control'%>
		<br>
		<%= f.label "Pago conductor" %>
		<%= f.text_field :driver_price, class: 'form-control'%>
		<br>
		<p>Camion</p>
		<%= f.select(:truck, [['0504 FYH',1], ['7636 DYV',2], ['7007 BJP',3], ['6127 DGD',4], ['4584 FKH',5], ['4605 CTW',6], ['SIN MATRICULA', 7]], {include_blank: "Seleccionar camión"}, {:class => 'browser-default'}) %>
		<br>
		<p>Conductor</p>
		<%= f.select(:driver, [['PEPE',1], ['JESUS',2], ['DAVID',3], ['CARLOS',4], ['TERESA',5], ['ROBERTO',6], ['OTROS', 7]], {include_blank: "Seleccionar conductor"}, {:class => 'browser-default'}) %>
		<br>
		<p>Estado</p>
		<%= f.select(:delivery_status, ['PENDIENTE','CARGADO', 'ENTREGADO', 'CANCELADO'], {include_blank: "Seleccionar estado"}, {:class => 'browser-default'}) %>
		<%= f.label "Fecha de entrega" %>
		<%= f.date_field :delivery_date, class: 'browser-default'%>
		<br>
		<%= f.label "Método de pago" %>
		<%= f.select(:payment_method, ['Efectivo', 'Transferencia', 'Recibo'], {include_blank: "Seleccionar metodo de pago"}, {:class => 'browser-default'}) %>
		<br>
		<%= f.label "Estado del pago" %>
		<%= f.select(:payment_status, ['PENDIENTE','PAGADO'], {include_blank: "Selecionar estado"}, {:class => 'browser-default'}) %>
		<br>
		<%= f.label "Fecha de pago" %>
		<%= f.date_field :payment_date, class: 'browser-default' %>
		<br>
  		<%= f.submit "Guardar cambios" %>
  	<% end %>
</div>

app/views/deliveries/index.html.erb
<div class="deliveries">
	<ul class="collection with-header">	
				<% @deliveries.order(id: :asc).each do |delivery| %>
						<li class="collection-item">Pedido Nº: <%= delivery.id %> - <%= @vehicles.find_by(delivery_id: delivery.id).bastidor_matricula %> - <%= @vehicles.find_by(delivery_id: delivery.id).brand %> - <%= @vehicles.find_by(delivery_id: delivery.id).model %> - <%= @places.find(delivery.origin).city %> a <%= @places.find(delivery.destination).city %> - <%= delivery.client.name %> <%= link_to('Editar', edit_client_delivery_path(delivery.client.id, delivery.id)) %> - <%= link_to('Mostrar', client_delivery_path(delivery.client.id, delivery.id)) %> <%= link_to 'Eliminar',  client_delivery_path(delivery.client.id, delivery.id) ,  method: :delete, data: { confirm: '¿Estas seguro?' } %></li>
			<% end %>
	</ul>
</div>

app/views/deliveries/new.html.erb
<div class="new-delivery">
  <div class="row">
    <form class="col s12" action="/clients/<%=@client.id%>/deliveries" method="POST" enctype="multipart/form-data">
      <h3>Solicitud para cliente: <%= @client.name %></h3>
      <h4>Información del vehículo</h4>
      <div class="row">
        <div class="input-field col s12">
          <input name="basmat" placeholder="Matrícula o bastidor" id="basmat" type="text" class="validate">
          <label for="basmat">Matricula/Bastidor</label>
        </div>
        </div>
        <div class="row">
        <div class="input-field col s6">
          <input name="marca" placeholder="Marca" id="marca" type="text" class="validate">
          <label for="marca">Marca</label>
        </div>
        <div class="input-field col s6">
          <input name="modelo" placeholder="Modelo" id="modelo" type="text" class="validate">
          <label for="modelo">Modelo</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <textarea name="observaciones" class="materialize-textarea"></textarea>
          <label for="observaciones">Observaciones</label>
        </div>
      </div>
      <h4>Recoger en:</h4>
      <div class="row">
        <div class="input-field col s12">
          <input name="origenEmpresa" id="origenEmpresa" type="text">
          <label for="origenEmpresa">Empresa</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input name="origenDireccion" id="origenDireccion" type="text">
          <label for="origenDireccion">Dirección</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input name="origenDetalles" id="origenDetalles" type="text">
          <label for="origenDetalles">Detalles dirección</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <input name="origenCP" id="origenCP" type="text">
          <label for="origenCP">Código postal</label>
        </div>
        <div class="input-field col s6">
          <input name="origenCiudad" id="origenCiudad" type="text">
          <label for="origenCiudad">Ciudad</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <input name="origenTelefono" id="origenTelefono" type="text">
          <label for="origenTelefono">Telefono</label>
        </div>
        <div class="input-field col s6">
          <input name="origenContacto" id="origenContacto" type="text">
          <label for="origenContacto">Persona de contacto</label>
        </div>
      </div>
      <h4>Entregar en:</h4>
      <div class="row">
        <div class="input-field col s12">
          <input name="destinoEmpresa" id="destinoEmpresa" type="text">
          <label for="destinoEmpresa">Empresa</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input name="destinoDireccion" id="destinoDireccion" type="text">
          <label for="destinoDireccion">Dirección</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input name="destinoDetalles" id="destinoDetalles" type="text">
          <label for="destinoDetalles">Detalles dirección</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <input name="destinoCP" id="destinoCP" type="text">
          <label for="destinoCP">Código postal</label>
        </div>
        <div class="input-field col s6">
          <input name="destinoCiudad" id="destinoCiudad" type="text">
          <label for="destinoCiudad">Ciudad</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <input name="destinoTelefono" id="destinoTelefono" type="text">
          <label for="destinoTelefono">Telefono</label>
        </div>
        <div class="input-field col s6">
          <input name="destinoContacto" id="destinoContacto" type="text">
          <label for="destinoContacto">Persona de contacto</label>
        </div>
      </div>
      <div id="upload">
          <input type="file" id="file-select" name="picture"/>
      </div>
        <br><br><br>
      <input type="submit" value="Enviar solicitud">
    </form>
  </div>
</div>        

app/views/deliveries/pendientes.html.erb
<div class="pendientes" id="dvData">
	<table class="responsive-table">
		<thead>
			<tr>
				<th>Pedido</th>
				<th>Cliente</th>
				<th>Bast/Mat</th>
				<th>Marca/Modelo</th>
				<th>Origen</th>
				<th>Destino</th>
				<th><div class="row"><div class="input-field col s2">Precio</div><div class="input-field col s2">Precio Conductor</div><div class="input-field col s2">Asignar camion</div><div class="input-field col s2">Asignar conductor</div><div class="input-field col s2">Estado</div><div class="input-field col s2">Guardar</div></div></th>
			</tr>
		</thead>
		<tbody>
			<% @deliveries.each do |delivery| %>
				<tr>
					<td><%= delivery.id %></td>
					<td><%= delivery.client.name %></td>
					<td><%= @vehicles.find_by(id: delivery.vehicle).bastidor_matricula %></td>
					<td><%= @vehicles.find(delivery.vehicle).brand %> - <%= @vehicles.find(delivery.vehicle).model %></td>
					<td><%= @places.find(delivery.origin).name %> - <%= @places.find(delivery.origin).city %> - <%= @places.find(delivery.origin).postal_code %></td>
					<td><%= @places.find(delivery.destination).name %> - <%= @places.find(delivery.destination).city %> - <%= @places.find(delivery.destination).postal_code %></td>
					
						<td><form name="<%=delivery.id%>" action="/update/pendientes/<%=delivery.id%>" method="POST">
						<div class="row">
						<div class="input-field col s2">
						<input	class="browser-default" type="text" name="precio">
						</div>
						<div class="input-field col s2">
						<input	class="browser-default" type="text" name="precioConductor">
						</div>
						<div class="input-field col s2">
						<select class="browser-default" name="camion">
							<option value="1">0504FYH</option>
							<option value="2">7636DYV</option>
							<option value="3">7007BJP</option>
							<option value="4">6127DGD</option>
							<option value="5">4584FKH</option>
							<option value="6">4605CTW</option>
							<option value="7">BOXER</option>
						</select>
						</div>
						<div class="input-field col s2">	
						<select class="browser-default" name="conductor">
							<option value="1">Pepe</option>
							<option value="2">Jesus</option>
							<option value="3">David</option>
							<option value="4">Carlos</option>
							<option value="5">Teresa</option>
							<option value="6">Roberto</option>
							<option value="7">Otros</option>
						</select>
						</div>
						<div class="input-field col s2">
						<select class="browser-default" name="estado">
							<option value="PENDIENTE">PENDIENTE</option>
							<option value="CARGADO">CARGADO</option>
							<option value="ENTREGADO">ENTREGADO</option>
							<option value="CANCELADO">CANCELADO</option>
						</select>
						</div>
						<div class="input-field col s2">
						<input	type="submit" name="commit<%=delivery.id%>" value="Guardar">
						</div>
						</form>
						</div>
						</td>
					
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<button id="btnExport">Exportar a excel</button>
<script type="text/javascript">
	$(document).ready(function() {
    $("#btnExport").click(function(e) {
        //getting values of current time for generating the file name
        var dt = new Date();
        var day = dt.getDate();
        var month = dt.getMonth() + 1;
        var year = dt.getFullYear();
        var hour = dt.getHours();
        var mins = dt.getMinutes();
        var postfix = day + "." + month + "." + year + "_" + hour + "." + mins;
        //creating a temporary HTML link element (they support setting file names)
        var a = document.createElement('a');
        //getting data from our div that contains the HTML table
        var data_type = 'data:application/vnd.ms-excel';
        var table_div = document.getElementById('dvData');
        var table_html = table_div.outerHTML.replace(/ /g, '%20');
        a.href = data_type + ', ' + table_html;
        //setting the file name
        a.download = 'exported_table_' + postfix + '.xls';
        //triggering the function
        a.click();
        //just in case, prevent default behaviour
        e.preventDefault();
    });
});
</script>

app/views/deliveries/show.html.erb
<div class="delivery">
	<h5>Solicitud Nº: <%= @delivery.id %> para cliente: <%= @client.name %> - CONFIRMADA</h5>
	<h6>Informacion del vehículo - <a href="<%= @delivery.document.url(:original, false) %>"> Descarga autorizacion </a></h6>
	<div class="row">
        <div class="col s12 m12">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title"><%= @vehicle.brand %> - <%= @vehicle.model %></span>
              <p>Bastidor o Matricula: <%= @vehicle.bastidor_matricula %></p>
              <p>Observaciones: <%= @vehicle.observations %></p>
            </div>
          </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m12">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">Origen</span>
              	<p>Empresa: <%= @origin.name %></p>
              	<p>Direccion: <%= @origin.address %></p>
              	<p>Detalles dirección: <%= @origin.address_details %></p>
              	<p>Ciudad: <%= @origin.city %> - Código postal: <%= @origin.postal_code %></p>
              	<p>Telefono contacto: <%= @origin.phone %></p>
              	<p>Persona de contacto: <%= @origin.contact_person %></p>
            </div>
          </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m12">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">Destino</span>
              	<p>Empresa: <%= @destiny.name %></p>
              	<p>Direccion: <%= @destiny.address %></p>
              	<p>Detalles dirección: <%= @destiny.address_details %></p>
              	<p>Ciudad: <%= @destiny.city %> - Código postal: <%= @destiny.postal_code %></p>
              	<p>Telefono contacto: <%= @destiny.phone %></p>
              	<p>Persona de contacto: <%= @destiny.contact_person %></p>
            </div>
          </div>
        </div>
    </div>
    <% if(@delivery.delivery_status != "PENDIENTE") %>
      <div class="row">
          <div class="col s12 m12">
            <div class="card blue-grey darken-1">
              <div class="card-content white-text">
                <span class="card-title">Informacion adicional</span>
                  <p>Precio: <%= @delivery.price %></p>
                  <p>Precio conductor: <%= @delivery.driver_price %></p>
                  <p>Camion asignado: <%= @truck.find(@delivery.truck).matricula %></p>
                  <p>Conductor asignado: <%= @driver.find(@delivery.driver).name %></p>
                  <p>Estado: <%= @delivery.delivery_status %> </p>
              </div>
            </div>
          </div>
      </div>
    <% end %>
</div>

app/views/deliveries/ver_cargas.html.erb
<div class="cargas">
	<% @trucks.each do |truck| %>
		<ul class="collection with-header">	
			<li class="collection-header grey"><h6><%= truck.matricula %> - <%= truck.marca %> - <%= truck.modelo %> - Total cargados: <%= @deliveries.where(truck: truck.id).count %> - <%= link_to('Mostrar', truck_path(truck), :class => "waves-effect waves-light btn green") %></h6></li>
				<% @deliveries.each do |delivery| %>
					<% if delivery.truck == truck.id %>
						<li class="collection-item"><%= @vehicles.find_by(delivery_id: delivery.id).bastidor_matricula %> - <%= @vehicles.find_by(delivery_id: delivery.id).brand %> - <%= @vehicles.find_by(delivery_id: delivery.id).model %> - <%= @places.find(delivery.origin).city %> a <%= @places.find(delivery.destination).city %> - <%= delivery.client.name %> <%= link_to('Editar', edit_client_delivery_path(delivery.client.id, delivery.id)) %> </li>
					<% end %>
				<% end %>
		</ul>
	<% end %>
</div>