config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get "/" => "site#home"

  get "/clientuser" => "site#clientuser"

  get "/pendientes" => "deliveries#pendientes"

  post "/update/pendientes/:id" => "deliveries#pending"

  get "/ver_cargas" => "deliveries#ver_cargas"

  get "/transportes" => "deliveries#index"

  post "/customreport" => "site#customreport"

  post "/deliveredreport" => "site#deliveredreport"

  post "/patsea" => "site#patsea"

  resources :clients, only: [:update, :edit, :show, :new, :index, :create, :destroy] do
  	resources :deliveries, only: [ :update, :edit, :show, :new, :create, :destroy]
  end

  resources :trucks, only: [:update, :edit, :show, :new, :index, :create, :destroy]

  resources :drivers, only: [:update, :edit, :show, :new, :index, :create, :destroy]
end

app/controllers/site_controller.rb
require 'pry'

class SiteController < ApplicationController
	def home
		@deliveries = Delivery.where(delivery_status: "PENDIENTE")
		@clients = Client.all
		@trucks = Truck.all
		@drivers = Driver.all
		@vehicles = Vehicle.all
		@places = Place.all
		@clientdeliveries = Delivery.all

	end

	def clientuser
		@clients = Client.all
		@users = User.all
	end

	def patsea
		@filtered_vehiles = Vehicle.where("bastidor_matricula like ?", "%#{params[:basmat]}%" )
		@deliveries = []
		@filtered_vehiles.each do |t|
			if Delivery.find(t.delivery_id)
				@deliveries.push(Delivery.find(t.delivery_id))
			end
		end
		@vehicles = Vehicle.all
		@places = Place.all
	end

	def customreport

		@deliveriesfinal = []
		@cabecera = ['Filtros aplicados: ', 'Fecha desde: ', params[:date_from] , ' hasta ' , params[:date_to]]
		deliveries = Delivery.where(['DATE(created_at) >= ? AND DATE(created_at) <=?', Time.parse(params[:date_from]), Time.parse(params[:date_to])] )
		
		if params[:delivery_state] != "TODOS"
			deliveriesif = deliveries.where(['delivery_status = ?', params[:delivery_state]])
			@cabecera.push(' - Estado: ')
			@cabecera.push(params[:delivery_state])
		else
			deliveriesif = deliveries
			@cabecera.push(' - Estado: Todos')
		end

		if params[:client] != "TODOS"
			deliveriesclient = deliveriesif.where(['client_id = ?', params[:client]])
			@cabecera.push(' - Cliente: ')
			@cabecera.push(Client.find(params[:client]).name)
		else
			deliveriesclient = deliveriesif
			@cabecera.push(' - Cliente: TODOS')
		end

		if params[:camion] != "TODOS"
			deliveriestruck = deliveriesclient.where(['truck = ?', params[:camion]])
			@cabecera.push(' - Camion: ')
			@cabecera.push(Truck.find(params[:camion]).matricula)
		else
			deliveriestruck = deliveriesclient
			@cabecera.push(' - Camion: TODOS')
		end

		if params[:conductor] != "TODOS"
			deliveriesdriver = deliveriestruck.where(['driver = ?', params[:conductor]])
			@cabecera.push(' - Conductor: ')
			@cabecera.push(Driver.find(params[:conductor]).name)
		else
			deliveriesdriver = deliveriestruck
			@cabecera.push(' - Conductor: TODOS')
		end
		
		if params[:pagoestado] != "TODOS"
			deliveriespagoestado = deliveriesdriver.where(['payment_status = ?', params[:pagoestado]])
			@cabecera.push(' - Estado del pago: ')
			@cabecera.push(params[:pagoestado])
		else
			deliveriespagoestado = deliveriesdriver
			@cabecera.push(' - Estado del pago: TODOS')
		end

		if params[:pago] != "TODOS"
			@deliveriesfinal = deliveriespagoestado.where(['driver = ?', params[:pago]])
			@cabecera.push(' - Tipo de pago: ')
			@cabecera.push(params[:pago])
		else
			@deliveriesfinal = deliveriespagoestado
			@cabecera.push(' - Tipo de pago: TODOS')
		end


		@vehicles = Vehicle.all
		@places = Place.all
	end

	def deliveredreport

		@cabecera = ['Filtros aplicados: ', 'Fecha desde: ', params[:date_deliver] , ' hasta ' , params[:date_deliver_end]]
		@deliveriesfinal = []
		deliveries = Delivery.where(['DATE(delivery_date) >= ? AND DATE(delivery_date) <=?', Time.parse(params[:date_deliver]).beginning_of_day, Time.parse(params[:date_deliver_end]).end_of_day] )
		
		if params[:client] != "TODOS"
			deliveriesclient = deliveries.where(['client_id = ?', params[:client]])
			@cabecera.push(' - Cliente: ')
			@cabecera.push(Client.find(params[:client]).name)
		else
			deliveriesclient = deliveries
			@cabecera.push(' - Cliente: TODOS')
		end

		if params[:camion] != "TODOS"
			deliveriestruck = deliveriesclient.where(['truck = ?', params[:camion]])
			@cabecera.push(' - Camion: ')
			@cabecera.push(Truck.find(params[:camion]).matricula)
		else
			deliveriestruck = deliveriesclient
			@cabecera.push(' - Camion: TODOS')
		end

		if params[:conductor] != "TODOS"
			@deliveriesfinal = deliveriestruck.where(['driver = ?', params[:conductor]])
			@cabecera.push(' - Conductor: ')
			@cabecera.push(Driver.find(params[:conductor]).name)
		else
			@deliveriesfinal = deliveriestruck
			@cabecera.push(' - Conductor: TODOS')
		end
		@vehicles = Vehicle.all
		@places = Place.all
	end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/clientuser.html.erb
<div class="userForm">
	<ul class="collection">
	<% @users.each do |user| %>
		<li><%= link_to(user.email, edit_user_registration_path(user)) %></li>
	<% end %>
	</ul>
</div>

app/views/site/customreport.html.erb
<div id="dvData" class="customreport">
	<p>
	<% @cabecera.each do |t| %>
	<%= t %>
	<% end %>
	</p>
	<table class="responsive-table">
		<thead>
			<tr>
				<th>NºPedido</th>
				<th>Cliente</th>
				<th>Mod/Mar</th>
				<th>Bast/Mat</th>
				<th>Origen</th>
				<th>Destino</th>
				<th>Observaciones</th>
				<th>Precio</th>
				<th>Estado</th>
				<th>Fecha</th>
				<th>Metodo de pago</th>
				<th>Estado del pago</th>
			</tr>
		</thead>
		<tbody>
			<% total = 0 %>
			<% @deliveriesfinal.each do |delivery| %>
				<tr>
					<td><%= delivery.id %></td>
					<td><%= delivery.client.name %> -CIF: <%= delivery.client.nif %></td>
					<td><%= @vehicles.find(delivery.vehicle).brand %> -<%= @vehicles.find(delivery.vehicle).model %></td>
					<td><%= @vehicles.find(delivery.vehicle).bastidor_matricula %></td>
					<td><%= @places.find(delivery.origin).name %> - <%= @places.find(delivery.origin).address %> - <%= @places.find(delivery.origin).address_details %> - <%= @places.find(delivery.origin).city %> - <%= @places.find(delivery.origin).contact_person %></td>
					<td><%= @places.find(delivery.destination).name %> - <%= @places.find(delivery.destination).address %> - <%= @places.find(delivery.destination).address_details %> - <%= @places.find(delivery.destination).city %> - <%= @places.find(delivery.destination).contact_person %></td>
					<td><%= delivery.observations %></td>
					<td><%= delivery.price %>€</td>
					<td><%= delivery.delivery_status %></td>
					<td><% if delivery.delivery_status == "ENTREGADO" %>
							<%= delivery.delivery_date %>
						<% end %>
					</td>
					<td><%= delivery.payment_method %></td>
					<td><%= delivery.payment_status %></td>
				</tr>
				<% if delivery.price != nil %>
				<% total = total + delivery.price %>
				<% end %>
			<% end %>
		</tbody>
	</table>
	<div class="totales">
		<p>Total: <%= total %>€</p>
	</div>
</div>
<button id="btnExport">Exportar a excel</button>

app/views/site/deliveredreport.html.erb
<div class="customreport">
	<p>
	<% @cabecera.each do |t| %>
	<%= t %>
	<% end %>
	</p>
	<table class="responsive-table">
		<thead>
			<tr>
				<th>NºPedido</th>
				<th>Cliente</th>
				<th>Mod/Mar</th>
				<th>Bast/Mat</th>
				<th>Origen</th>
				<th>Destino</th>
				<th>Precio</th>
			</tr>
		</thead>
		<tbody>
			<% @deliveriesfinal.each do |delivery| %>
				<tr>
					<td><%= delivery.id %></td>
					<td><%= delivery.client.name %></td>
					<td><%= @vehicles.find(delivery.vehicle).brand %> -<%= @vehicles.find(delivery.vehicle).model %></td>
					<td><%= @vehicles.find(delivery.vehicle).bastidor_matricula %></td>
					<td><%= @places.find(delivery.origin).name %> - <%= @places.find(delivery.origin).address %> - <%= @places.find(delivery.origin).city %></td>
					<td><%= @places.find(delivery.destination).name %> - <%= @places.find(delivery.destination).address %> - <%= @places.find(delivery.destination).city %></td>
					<td><%= delivery.price %>€</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/site/home.html.erb
<% if user_signed_in? %>
	<% if current_user.role == "admin" %>
<div class="wrapper">
	<div class="notifications">
		<h4>Notificaciones</h4>
		<br>
		<% if @deliveries.count > 0 %>
			<p> Tienes <%= @deliveries.count %> solicitudes pendientes </p>
			<a href="/pendientes">Ver solicitudes</a>
		<% else %>
			<p>No hay notificaciones</p>
		<% end %>
	</div>
	<div class="menu">
	<h5>Clientes</h5>
		<a class="waves-effect waves-light btn green" href="/clients"> Ver clientes </a>
		<a class="waves-effect waves-light btn green" href="/clients/new"> Nuevo cliente </a>
	<h5>Camiones</h5>
		<a class="waves-effect waves-light btn blue" href="/trucks"> Ver camiones </a>
		<a class="waves-effect waves-light btn blue" href="/trucks/new"> Nuevo camion </a>
		<a class="waves-effect waves-light btn blue" href="/ver_cargas"> Ver cargas </a>
	<h5>Conductores</h5>
		<a class="waves-effect waves-light btn purple" href="/drivers"> Ver conductores </a>
		<a class="waves-effect waves-light btn purple" href="/drivers/new"> Nuevo conductor </a>
	<h5>Transportes</h5>
		<a class="waves-effect waves-light btn red" href="/transportes">Solicitudes</a> 
		<form action="/patsea" method="POST">
			<div class="input-field"><input placeholder="Matrícula o bastidor" name="basmat" type="text"></div>
			<input class="waves-effect waves-light btn red" type="submit" value="Buscar">
		</form>
	</div>
</div>
<div class="reports">
	<h5>Busqueda por fecha de creación</h5>
	<div class="row">
		<form action="/customreport" method="POST">
			<div class="input-field col s2">
				<p>Desde</p>
				<input name="date_from" type="date" class="datepicker">
			</div>
			<div class="input-field col s2">
				<p>hasta</p>
				<input name="date_to" type="date" class="datepicker">
			</div>
			<div class="input-field col s1">
    			<p>Estado</p>
    			<select name="delivery_state" class="browser-default">
			      <option value="TODOS">Cualquiera</option>
			      <option value="PENDIENTE">PENDIENTE</option>
			      <option value="CARGADO">CARGADO</option>
			      <option value="ENTREGADO">ENTREGADO</option>
			      <option value="CANCELADO">CANCELADO</option>
    			</select>
  			</div>
  			<div class="input-field col s2">
    			<p>Cliente</p>
    			<select name="client" class="browser-default">
			      <option value="TODOS">Cualquiera</option>
			      <% @clients.each do |client| %>
			      	<option value="<%=client.id%>"><%=client.name%></option>
			      <% end %>
    			</select>
  			</div>
  			<div class="input-field col s1">
    			<p>Camion</p>
    			<select name="camion" class="browser-default">
			      <option value="TODOS">Cualquiera</option>
			      <% @trucks.each do |truck| %>
			      	<option value="<%=truck.id%>"><%=truck.matricula%></option>
			      <% end %>
    			</select>
  			</div>
  			<div class="input-field col s1">
    			<p>Conductor</p>
    			<select name="conductor" class="browser-default">
			      <option value="TODOS">Cualquiera</option>
			      <% @drivers.each do |driver| %>
			      	<option value="<%=driver.id%>"><%=driver.name%></option>
			      <% end %>
    			</select>
  			</div>
  			<div class="input-field col s1">
    			<p>Estado pago</p>
    			<select name="pagoestado" class="browser-default">
			      <option value="TODOS">Cualquiera</option>
			       	<option value="PENDIENTE">PENDIENTE</option>
			       	<option value="PAGADO">PAGADO</option>
			      </select>
  			</div>
  			<div class="input-field col s1">
    			<p>Pago</p>
    			<select name="pago" class="browser-default">
			      <option value="TODOS">Cualquiera</option>
			       	<option value="Efectivo">Efectivo</option>
			       	<option value="Transferencia">Transferencia</option>
			       	<option value="Recibo">Recibo</option>
			      </select>
  			</div>
  			<div class="submitbutton">
				<input type="submit" value="Buscar">
			</div>
		</form>
	</div>
</div>

<div class="reports">
	<h5>Busqueda por fecha de entrega</h5>
	<div class="row">
		<form action="/deliveredreport" method="POST">
			<div class="input-field col s2">
				<p>Fecha de entrega desde</p>
				<input name="date_deliver" type="date" class="datepicker">
			</div>
			<div class="input-field col s2">
				<p>Fecha de entrega hasta</p>
				<input name="date_deliver_end" type="date" class="datepicker">
			</div>
  			<div class="input-field col s2">
    			<p>Cliente</p>
    			<select name="client" class="browser-default">
			      <option value="TODOS">Cualquiera</option>
			      <% @clients.each do |client| %>
			      	<option value="<%=client.id%>"><%=client.name%></option>
			      <% end %>
    			</select>
  			</div>
  			<div class="input-field col s2">
    			<p>Camion</p>
    			<select name="camion" class="browser-default">
			      <option value="TODOS">Cualquiera</option>
			      <% @trucks.each do |truck| %>
			      	<option value="<%=truck.id%>"><%=truck.matricula%></option>
			      <% end %>
    			</select>
  			</div>
  			<div class="input-field col s2">
    			<p>Conductor</p>
    			<select name="conductor" class="browser-default">
			      <option value="TODOS">Cualquiera</option>
			      <% @drivers.each do |driver| %>
			      	<option value="<%=driver.id%>"><%=driver.name%></option>
			      <% end %>
    			</select>
  			</div>
  			<div class="submitbutton">
				<input type="submit" value="Buscar">
			</div>
		</form>
	</div>
</div>
<% else %>
<div class="midcontent">
	<p>Acciones disponibles</p>
	<a class="waves-effect waves-light btn green" href="/clients/<%= current_user.assigned_client %>/deliveries/new"> Nueva solicitud </a>
	<h2>Listado de solicitudes</h2>
	<% if @clientdeliveries.where(client_id: current_user.assigned_client).count > 0 %>
	<table class="responsive-table">
		<thead>
			<tr>
			<th>Vehiculo</th>
			<th>Origen</th>
			<th>Destino</th>
			<th>Estado</th>
			</tr>
		</thead>
		<% @clientdeliveries.where(client_id: current_user.assigned_client).each do |delivery| %>
		<tr>
			<td><%= @vehicles.find_by(id: delivery.vehicle).bastidor_matricula %> - <%= @vehicles.find_by(id: delivery.vehicle).brand %> - <%= @vehicles.find_by(id: delivery.vehicle).model %></td>
			<td><%= @places.find(delivery.origin).name %> - <%= @places.find(delivery.origin).city %> - <%= @places.find(delivery.origin).postal_code %></td>
			<td><%= @places.find(delivery.destination).name %> - <%= @places.find(delivery.destination).city %> - <%= @places.find(delivery.destination).postal_code %></td>
			<td>
				<% if delivery.delivery_status == "PENDIENTE" %>
					ASIGNADO
					<% else %>
			<%= delivery.delivery_status %>
					<%end%>
			 <% if delivery.delivery_status == "ENTREGADO" %>
			 	<%= delivery.delivery_date %>
			 <% end %>
			 </td>
		</tr>
		<% end %>
	<% end %>
</div>
<% end %>

<% else %> 
<div class="midcontent">
	<h2>Gruas Martin Delgado</h2>
	<h5>Plataforma Web para clientes</h5>
	<img src="/main.jpg">
	<p>Para acceder a la plataforma ingrese su usario y contraseña <a href="/users/sign_in">aquí.</a></p>
</div>
<% end %>

app/views/site/patsea.html.erb
<div class="deliveries">
	<ul class="collection with-header">	
				<% @deliveries.each do |delivery| %>
						<li class="collection-item">Pedido Nº: <%= delivery.id %> - <%= @vehicles.find_by(delivery_id: delivery.id).bastidor_matricula %> - <%= @vehicles.find_by(delivery_id: delivery.id).brand %> - <%= @vehicles.find_by(delivery_id: delivery.id).model %> - <%= @places.find(delivery.origin).city %> a <%= @places.find(delivery.destination).city %> - <%= delivery.client.name %> <%= link_to('Editar', edit_client_delivery_path(delivery.client.id, delivery.id)) %> - <%= link_to('Mostrar', client_delivery_path(delivery.client.id, delivery.id)) %> <%= link_to 'Eliminar',  client_delivery_path(delivery.client.id, delivery.id) ,  method: :delete, data: { confirm: '¿Estas seguro?' } %></li>
			<% end %>
	</ul>
</div>