config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get "/" => "site#home"

  get "/clientuser" => "site#clientuser"

  get "/pendientes" => "deliveries#pendientes"

  post "/update/pendientes/:id" => "deliveries#pending"

  get "/ver_cargas" => "deliveries#ver_cargas"

  get "/transportes" => "deliveries#index"

  post "/customreport" => "site#customreport"

  post "/deliveredreport" => "site#deliveredreport"

  post "/patsea" => "site#patsea"

  resources :clients, only: [:update, :edit, :show, :new, :index, :create, :destroy] do
  	resources :deliveries, only: [ :update, :edit, :show, :new, :create, :destroy]
  end

  resources :trucks, only: [:update, :edit, :show, :new, :index, :create, :destroy]

  resources :drivers, only: [:update, :edit, :show, :new, :index, :create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gruas Martin Delgado Intranet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
</head>
<body>

	<div class="navbar-fixed">

		<ul id="dropdown-clients" class="dropdown-content">
  			<li><%= link_to("Ver clientes", clients_path) %> </a></li>
  			<li><%= link_to("Nuevo cliente", new_client_path) %></li>
		</ul>

    <ul id="dropdown-trucks" class="dropdown-content">
        <li><%= link_to("Ver camiones", trucks_path) %> </a></li>
        <li><%= link_to("Nuevo camion", new_truck_path) %></li>
    </ul>
	
		<nav>
    		<div class="nav-wrapper">
      			<a class="brand-logo" href="/"><img id="logo" src="/logopresta.png"></a>
      			<ul id="nav-mobile" class="right">
                <% if user_signed_in? %>
                <li>Conectado como: <%= current_user.email %></li>
                <li><%= link_to 'Desconectarse', destroy_user_session_path, method: 'DELETE' %></li>
                <% else %>
                <li><%= link_to 'Iniciar sesion', new_user_session_path, method: 'GET' %></li>
                <% end %>
            </ul>
    		</div>
  		</nav>
	
	</div>

<%= yield %>

</body>
</html>